import { Step } from '@/types/forms';

export const formSteps: Step[] = [
  {
    id: 'contact',
    title: 'Contact Info',
    fields: [
      'fullName',
      'email',
      'phone',
      'address.street',
      'address.city',
      'address.state',
      'address.zipCode',
      'billingAddressSame',
      'preferredContactMethod',
    ],
  },
  {
    id: 'equipment',
    title: 'Equipment',
    fields: [
      'equipmentType',
      'makeBrand',
      'modelNumber',
      'serialNumber',
      'yearOfManufacture',
    ],
  },
  {
    id: 'problem',
    title: 'Problem',
    fields: [
      'problemDescription',
      'problemStarted',
      'recentMaintenance',
      'lastServiceDate',
    ],
  },
  {
    id: 'service',
    title: 'Service',
    fields: [
      'isMobileRepair',
      'preferredServiceDate',
      'preferredTimeWindow',
      'equipmentLocation',
      'specialInstructions',
    ],
  },
  {
    id: 'agreements',
    title: 'Agreements',
    fields: [
      'diagnosticFeeAcknowledged',
      'diagnosticAuthorization',
      'termsAccepted',
    ],
  },
];

export const timeWindows = [
  { value: 'morning', label: 'Morning (8 AM - 12 PM)' },
  { value: 'afternoon', label: 'Afternoon (12 PM - 4 PM)' },
  { value: 'evening', label: 'Evening (4 PM - 7 PM)' },
  { value: 'flexible', label: 'Flexible (Any Time)' },
];

export const equipmentTypes = [
  { value: 'lawn-mower', label: 'Lawn Mower' },
  { value: 'chainsaw', label: 'Chainsaw' },
  { value: 'string-trimmer', label: 'String Trimmer' },
  { value: 'leaf-blower', label: 'Leaf Blower' },
  { value: 'hedge-trimmer', label: 'Hedge Trimmer' },
  { value: 'pressure-washer', label: 'Pressure Washer' },
  { value: 'snow-blower', label: 'Snow Blower' },
  { value: 'tiller', label: 'Tiller' },
  { value: 'generator', label: 'Generator' },
  { value: 'other', label: 'Other' },
];

export const contactMethods = [
  { value: 'phone', label: 'Phone Call' },
  { value: 'email', label: 'Email' },
  { value: 'text', label: 'Text Message' },
];

// States array with Florida at the top
export const states = [
  { value: 'FL', label: 'Florida' },
  ...[
    { value: 'AL', label: 'Alabama' },
    { value: 'AK', label: 'Alaska' },
    { value: 'AZ', label: 'Arizona' },
    { value: 'AR', label: 'Arkansas' },
    { value: 'CA', label: 'California' },
    { value: 'CO', label: 'Colorado' },
    { value: 'CT', label: 'Connecticut' },
    { value: 'DE', label: 'Delaware' },
    { value: 'GA', label: 'Georgia' },
    { value: 'HI', label: 'Hawaii' },
    { value: 'ID', label: 'Idaho' },
    { value: 'IL', label: 'Illinois' },
    { value: 'IN', label: 'Indiana' },
    { value: 'IA', label: 'Iowa' },
    { value: 'KS', label: 'Kansas' },
    { value: 'KY', label: 'Kentucky' },
    { value: 'LA', label: 'Louisiana' },
    { value: 'ME', label: 'Maine' },
    { value: 'MD', label: 'Maryland' },
    { value: 'MA', label: 'Massachusetts' },
    { value: 'MI', label: 'Michigan' },
    { value: 'MN', label: 'Minnesota' },
    { value: 'MS', label: 'Mississippi' },
    { value: 'MO', label: 'Missouri' },
    { value: 'MT', label: 'Montana' },
    { value: 'NE', label: 'Nebraska' },
    { value: 'NV', label: 'Nevada' },
    { value: 'NH', label: 'New Hampshire' },
    { value: 'NJ', label: 'New Jersey' },
    { value: 'NM', label: 'New Mexico' },
    { value: 'NY', label: 'New York' },
    { value: 'NC', label: 'North Carolina' },
    { value: 'ND', label: 'North Dakota' },
    { value: 'OH', label: 'Ohio' },
    { value: 'OK', label: 'Oklahoma' },
    { value: 'OR', label: 'Oregon' },
    { value: 'PA', label: 'Pennsylvania' },
    { value: 'RI', label: 'Rhode Island' },
    { value: 'SC', label: 'South Carolina' },
    { value: 'SD', label: 'South Dakota' },
    { value: 'TN', label: 'Tennessee' },
    { value: 'TX', label: 'Texas' },
    { value: 'UT', label: 'Utah' },
    { value: 'VT', label: 'Vermont' },
    { value: 'VA', label: 'Virginia' },
    { value: 'WA', label: 'Washington' },
    { value: 'WV', label: 'West Virginia' },
    { value: 'WI', label: 'Wisconsin' },
    { value: 'WY', label: 'Wyoming' },
  ]
];

export const initialFormValues = {
  fullName: '',
  email: '',
  phone: '',
  address: {
    street: '',
    city: '',
    state: 'FL',
    zipCode: '',
  },
  billingAddressSame: true,
  billingAddress: {
    street: '',
    city: '',
    state: 'FL',
    zipCode: '',
  },
  preferredContactMethod: 'phone',
  equipmentType: '',
  equipmentTypeOther: '',
  makeBrand: '',
  modelNumber: '',
  serialNumber: '',
  yearOfManufacture: '',
  problemDescription: '',
  problemStarted: '',
  recentMaintenance: false,
  lastServiceDate: '',
  isMobileRepair: false,
  preferredServiceDate: '',
  preferredTimeWindow: 'flexible',
  equipmentLocation: '',
  specialInstructions: '',
  diagnosticFeeAcknowledged: false,
  diagnosticAuthorization: false,
  termsAccepted: false,
};
